name: Build and deploy ASP.Net Core app to Azure Web App - eurovisiononmars

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore src/EurovisionOnMars.Api/EurovisionOnMars.Api.csproj

      - name: Build the app
        run: dotnet build src/EurovisionOnMars.Api/EurovisionOnMars.Api.csproj --configuration Release --no-restore

      - name: Publish the app
        run: dotnet publish src/EurovisionOnMars.Api/EurovisionOnMars.Api.csproj --configuration Release --output ./myapp

      - name: Upload published app as artifact
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download published artifact
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: myapp

      - name: Zip published output
        run: |
          cd myapp
          zip -r ../app.zip .

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4BA2B91BDF164A56BCB3A67C571990BA }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3A8243102DE94B8AA65AD873C015BEC7 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2CF11501E0D243149E45A5E2574C1397 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'eurovisiononmars'
          slot-name: 'Production'
          package: app.zip
